version: "3.8"

services:
  db_walkeat:
    image: postgres:latest
    container_name: db_walkeat
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  back:
    container_name: walkeat
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py collectstatic
        --no-input && gunicorn -b 0.0.0.0:8000 walkeat_backends.wsgi --reload"
    env_file:
      - .env
    volumes:
      - .:/app
      - ./static:/static
    ports:
      - "8080:8080"
    depends_on:
      - db_walkeat
    links:
      - db_walkeat

volumes:
  postgres_data: