# Generated by Django 4.1 on 2022-08-15 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('sets', 'sets'), ('lunch', 'lunch'), ('breakfast', 'breakfast'), ('dinner', 'dinner'), ('salad', 'salad'), ('drink', 'drink')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Fit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, default='media/food.svg', upload_to='uploaded_media')),
                ('title', models.CharField(max_length=35)),
                ('calories', models.FloatField(default=0.0)),
                ('carbohydrates', models.FloatField(default=0.0)),
                ('protein', models.FloatField(default=0.0)),
                ('fats', models.FloatField(default=0.0)),
                ('price', models.FloatField(default=0.0)),
                ('ingredients', models.CharField(blank=True, max_length=255, null=True)),
                ('kcal', models.FloatField(blank=True, default=0.0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu_api.category')),
            ],
        ),
    ]
