# Generated by Django 4.1 on 2022-08-15 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('sets', 'sets'), ('lunch', 'lunch'), ('breakfast', 'breakfast'), ('dinner', 'dinner'), ('salad', 'salad'), ('drink', 'drink')], max_length=255, unique=True),
        ),
        migrations.RemoveField(
            model_name='fit',
            name='category',
        ),
        migrations.AddField(
            model_name='fit',
            name='category',
            field=models.ManyToManyField(to='menu_api.category'),
        ),
    ]
