# Generated by Django 4.1 on 2022-08-28 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("menu_api", "0001_initial"),
        ("user_api", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="card",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="user_api.card"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="cart",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="menu_api.cart"
            ),
        ),
        migrations.AddField(
            model_name="fit",
            name="category",
            field=models.ManyToManyField(
                related_name="categories", to="menu_api.category"
            ),
        ),
        migrations.AddField(
            model_name="cart",
            name="food",
            field=models.ManyToManyField(null=True, to="menu_api.fit"),
        ),
        migrations.AddField(
            model_name="cart",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
